// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManager.DatabaseContext;

#nullable disable

namespace TaskManager_Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240211102356_taskStatus")]
    partial class taskStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TaskManager.Identity.ApplicationRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("TaskManager.Identity.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("ReceivesNewsLetter")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("TaskManager_Core.Domain.Entities.ClientLocation", b =>
                {
                    b.Property<int>("ClientLocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientLocationId"));

                    b.Property<string>("ClientLocationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClientLocationId");

                    b.ToTable("ClientLocations");

                    b.HasData(
                        new
                        {
                            ClientLocationId = 1,
                            ClientLocationName = "Boston"
                        },
                        new
                        {
                            ClientLocationId = 2,
                            ClientLocationName = "New Delhi"
                        },
                        new
                        {
                            ClientLocationId = 3,
                            ClientLocationName = "New Jercy"
                        },
                        new
                        {
                            ClientLocationId = 4,
                            ClientLocationName = "New York"
                        },
                        new
                        {
                            ClientLocationId = 5,
                            ClientLocationName = "London"
                        },
                        new
                        {
                            ClientLocationId = 6,
                            ClientLocationName = "Tokyo"
                        });
                });

            modelBuilder.Entity("TaskManager_Core.Domain.Entities.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryId"));

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryId = 1,
                            CountryName = "China"
                        },
                        new
                        {
                            CountryId = 2,
                            CountryName = "United States"
                        },
                        new
                        {
                            CountryId = 3,
                            CountryName = "Indonesia"
                        },
                        new
                        {
                            CountryId = 4,
                            CountryName = "Brazil"
                        },
                        new
                        {
                            CountryId = 5,
                            CountryName = "Pakistan"
                        },
                        new
                        {
                            CountryId = 6,
                            CountryName = "Nigeria"
                        },
                        new
                        {
                            CountryId = 7,
                            CountryName = "Bangladesh"
                        },
                        new
                        {
                            CountryId = 8,
                            CountryName = "Russia"
                        },
                        new
                        {
                            CountryId = 9,
                            CountryName = "Japan"
                        },
                        new
                        {
                            CountryId = 10,
                            CountryName = "Mexico"
                        },
                        new
                        {
                            CountryId = 11,
                            CountryName = "Philippines"
                        },
                        new
                        {
                            CountryId = 12,
                            CountryName = "Vietnam"
                        },
                        new
                        {
                            CountryId = 13,
                            CountryName = "Ethiopia"
                        },
                        new
                        {
                            CountryId = 14,
                            CountryName = "Egypt"
                        },
                        new
                        {
                            CountryId = 15,
                            CountryName = "Germany"
                        },
                        new
                        {
                            CountryId = 16,
                            CountryName = "Iran"
                        },
                        new
                        {
                            CountryId = 17,
                            CountryName = "Turkey"
                        },
                        new
                        {
                            CountryId = 18,
                            CountryName = "Democratic Republic of the Congo"
                        },
                        new
                        {
                            CountryId = 19,
                            CountryName = "Thailand"
                        },
                        new
                        {
                            CountryId = 20,
                            CountryName = "France"
                        },
                        new
                        {
                            CountryId = 21,
                            CountryName = "United Kingdom"
                        },
                        new
                        {
                            CountryId = 22,
                            CountryName = "Italy"
                        },
                        new
                        {
                            CountryId = 23,
                            CountryName = "South Africa"
                        },
                        new
                        {
                            CountryId = 24,
                            CountryName = "South Korea"
                        },
                        new
                        {
                            CountryId = 25,
                            CountryName = "Myanmar"
                        },
                        new
                        {
                            CountryId = 26,
                            CountryName = "Spain"
                        },
                        new
                        {
                            CountryId = 27,
                            CountryName = "Colombia"
                        },
                        new
                        {
                            CountryId = 28,
                            CountryName = "Ukraine"
                        },
                        new
                        {
                            CountryId = 29,
                            CountryName = "Tanzania"
                        },
                        new
                        {
                            CountryId = 30,
                            CountryName = "Argentina"
                        },
                        new
                        {
                            CountryId = 31,
                            CountryName = "Kenya"
                        },
                        new
                        {
                            CountryId = 32,
                            CountryName = "Poland"
                        },
                        new
                        {
                            CountryId = 33,
                            CountryName = "Algeria"
                        },
                        new
                        {
                            CountryId = 34,
                            CountryName = "Canada"
                        },
                        new
                        {
                            CountryId = 35,
                            CountryName = "Uganda"
                        },
                        new
                        {
                            CountryId = 36,
                            CountryName = "Iraq"
                        },
                        new
                        {
                            CountryId = 37,
                            CountryName = "Morocco"
                        },
                        new
                        {
                            CountryId = 38,
                            CountryName = "Sudan"
                        },
                        new
                        {
                            CountryId = 39,
                            CountryName = "Peru"
                        },
                        new
                        {
                            CountryId = 40,
                            CountryName = "Malaysia"
                        },
                        new
                        {
                            CountryId = 41,
                            CountryName = "Uzbekistan"
                        },
                        new
                        {
                            CountryId = 42,
                            CountryName = "Saudi Arabia"
                        },
                        new
                        {
                            CountryId = 43,
                            CountryName = "Venezuela"
                        },
                        new
                        {
                            CountryId = 44,
                            CountryName = "Nepal"
                        },
                        new
                        {
                            CountryId = 45,
                            CountryName = "Afghanistan"
                        },
                        new
                        {
                            CountryId = 46,
                            CountryName = "Ghana"
                        },
                        new
                        {
                            CountryId = 47,
                            CountryName = "Yemen"
                        },
                        new
                        {
                            CountryId = 48,
                            CountryName = "North Korea"
                        },
                        new
                        {
                            CountryId = 49,
                            CountryName = "Mozambique"
                        },
                        new
                        {
                            CountryId = 50,
                            CountryName = "Taiwan"
                        },
                        new
                        {
                            CountryId = 51,
                            CountryName = "Australia"
                        },
                        new
                        {
                            CountryId = 52,
                            CountryName = "Syria"
                        },
                        new
                        {
                            CountryId = 53,
                            CountryName = "Ivory Coast"
                        },
                        new
                        {
                            CountryId = 54,
                            CountryName = "Madagascar"
                        },
                        new
                        {
                            CountryId = 55,
                            CountryName = "Angola"
                        },
                        new
                        {
                            CountryId = 56,
                            CountryName = "Sri Lanka"
                        },
                        new
                        {
                            CountryId = 57,
                            CountryName = "Cameroon"
                        },
                        new
                        {
                            CountryId = 58,
                            CountryName = "Romania"
                        },
                        new
                        {
                            CountryId = 59,
                            CountryName = "Kazakhstan"
                        },
                        new
                        {
                            CountryId = 60,
                            CountryName = "Netherlands"
                        },
                        new
                        {
                            CountryId = 61,
                            CountryName = "Chile"
                        },
                        new
                        {
                            CountryId = 62,
                            CountryName = "Niger"
                        },
                        new
                        {
                            CountryId = 63,
                            CountryName = "Burkina Faso"
                        },
                        new
                        {
                            CountryId = 64,
                            CountryName = "Ecuador"
                        },
                        new
                        {
                            CountryId = 65,
                            CountryName = "Guatemala"
                        },
                        new
                        {
                            CountryId = 66,
                            CountryName = "Mali"
                        },
                        new
                        {
                            CountryId = 67,
                            CountryName = "Malawi"
                        },
                        new
                        {
                            CountryId = 68,
                            CountryName = "Senegal"
                        },
                        new
                        {
                            CountryId = 69,
                            CountryName = "Cambodia"
                        },
                        new
                        {
                            CountryId = 70,
                            CountryName = "Zambia"
                        },
                        new
                        {
                            CountryId = 71,
                            CountryName = "Zimbabwe"
                        },
                        new
                        {
                            CountryId = 72,
                            CountryName = "Chad"
                        },
                        new
                        {
                            CountryId = 73,
                            CountryName = "Cuba"
                        },
                        new
                        {
                            CountryId = 74,
                            CountryName = "Belgium"
                        },
                        new
                        {
                            CountryId = 75,
                            CountryName = "Guinea"
                        },
                        new
                        {
                            CountryId = 76,
                            CountryName = "Greece"
                        },
                        new
                        {
                            CountryId = 77,
                            CountryName = "Tunisia"
                        },
                        new
                        {
                            CountryId = 78,
                            CountryName = "Portugal"
                        },
                        new
                        {
                            CountryId = 79,
                            CountryName = "Rwanda"
                        },
                        new
                        {
                            CountryId = 80,
                            CountryName = "Czech Republic"
                        },
                        new
                        {
                            CountryId = 81,
                            CountryName = "Haiti"
                        },
                        new
                        {
                            CountryId = 82,
                            CountryName = "Bolivia"
                        },
                        new
                        {
                            CountryId = 83,
                            CountryName = "Somalia"
                        },
                        new
                        {
                            CountryId = 84,
                            CountryName = "Hungary"
                        },
                        new
                        {
                            CountryId = 85,
                            CountryName = "Benin"
                        },
                        new
                        {
                            CountryId = 86,
                            CountryName = "Sweden"
                        },
                        new
                        {
                            CountryId = 87,
                            CountryName = "Belarus"
                        },
                        new
                        {
                            CountryId = 88,
                            CountryName = "Dominican Republic"
                        },
                        new
                        {
                            CountryId = 89,
                            CountryName = "Azerbaijan"
                        },
                        new
                        {
                            CountryId = 90,
                            CountryName = "Austria"
                        },
                        new
                        {
                            CountryId = 91,
                            CountryName = "Honduras"
                        },
                        new
                        {
                            CountryId = 92,
                            CountryName = "United Arab Emirates"
                        },
                        new
                        {
                            CountryId = 93,
                            CountryName = "South Sudan"
                        },
                        new
                        {
                            CountryId = 94,
                            CountryName = "Burundi"
                        },
                        new
                        {
                            CountryId = 95,
                            CountryName = "Switzerland"
                        },
                        new
                        {
                            CountryId = 96,
                            CountryName = "Israel"
                        },
                        new
                        {
                            CountryId = 97,
                            CountryName = "Tajikistan"
                        },
                        new
                        {
                            CountryId = 98,
                            CountryName = "Bulgaria"
                        },
                        new
                        {
                            CountryId = 99,
                            CountryName = "Serbia"
                        },
                        new
                        {
                            CountryId = 100,
                            CountryName = "Papua New Guinea"
                        },
                        new
                        {
                            CountryId = 101,
                            CountryName = "Paraguay"
                        },
                        new
                        {
                            CountryId = 102,
                            CountryName = "Laos"
                        },
                        new
                        {
                            CountryId = 103,
                            CountryName = "Libya"
                        },
                        new
                        {
                            CountryId = 104,
                            CountryName = "Jordan"
                        },
                        new
                        {
                            CountryId = 105,
                            CountryName = "Sierra Leone"
                        },
                        new
                        {
                            CountryId = 106,
                            CountryName = "Togo"
                        },
                        new
                        {
                            CountryId = 107,
                            CountryName = "El Salvador"
                        },
                        new
                        {
                            CountryId = 108,
                            CountryName = "Nicaragua"
                        },
                        new
                        {
                            CountryId = 109,
                            CountryName = "Eritrea"
                        },
                        new
                        {
                            CountryId = 110,
                            CountryName = "Denmark"
                        },
                        new
                        {
                            CountryId = 111,
                            CountryName = "Kyrgyzstan"
                        },
                        new
                        {
                            CountryId = 112,
                            CountryName = "Slovakia"
                        },
                        new
                        {
                            CountryId = 113,
                            CountryName = "Finland"
                        },
                        new
                        {
                            CountryId = 114,
                            CountryName = "Singapore"
                        },
                        new
                        {
                            CountryId = 115,
                            CountryName = "Turkmenistan"
                        },
                        new
                        {
                            CountryId = 116,
                            CountryName = "Norway"
                        },
                        new
                        {
                            CountryId = 117,
                            CountryName = "Costa Rica"
                        },
                        new
                        {
                            CountryId = 118,
                            CountryName = "Central African Republic"
                        },
                        new
                        {
                            CountryId = 119,
                            CountryName = "Ireland"
                        },
                        new
                        {
                            CountryId = 120,
                            CountryName = "Georgia"
                        },
                        new
                        {
                            CountryId = 121,
                            CountryName = "New Zealand"
                        },
                        new
                        {
                            CountryId = 122,
                            CountryName = "Republic of the Congo"
                        },
                        new
                        {
                            CountryId = 123,
                            CountryName = "Lebanon"
                        },
                        new
                        {
                            CountryId = 124,
                            CountryName = "Palestine"
                        },
                        new
                        {
                            CountryId = 125,
                            CountryName = "Croatia"
                        },
                        new
                        {
                            CountryId = 126,
                            CountryName = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            CountryId = 127,
                            CountryName = "Kuwait"
                        },
                        new
                        {
                            CountryId = 128,
                            CountryName = "Moldova"
                        },
                        new
                        {
                            CountryId = 129,
                            CountryName = "Liberia"
                        },
                        new
                        {
                            CountryId = 130,
                            CountryName = "Mauritania"
                        },
                        new
                        {
                            CountryId = 131,
                            CountryName = "Panama"
                        },
                        new
                        {
                            CountryId = 132,
                            CountryName = "Uruguay"
                        },
                        new
                        {
                            CountryId = 133,
                            CountryName = "Armenia"
                        },
                        new
                        {
                            CountryId = 134,
                            CountryName = "Lithuania"
                        },
                        new
                        {
                            CountryId = 135,
                            CountryName = "Albania"
                        },
                        new
                        {
                            CountryId = 136,
                            CountryName = "Oman"
                        },
                        new
                        {
                            CountryId = 137,
                            CountryName = "Mongolia"
                        },
                        new
                        {
                            CountryId = 138,
                            CountryName = "Jamaica"
                        },
                        new
                        {
                            CountryId = 139,
                            CountryName = "Lesotho"
                        },
                        new
                        {
                            CountryId = 140,
                            CountryName = "Namibia"
                        },
                        new
                        {
                            CountryId = 141,
                            CountryName = "Macedonia"
                        },
                        new
                        {
                            CountryId = 142,
                            CountryName = "Slovenia"
                        },
                        new
                        {
                            CountryId = 143,
                            CountryName = "Latvia"
                        },
                        new
                        {
                            CountryId = 144,
                            CountryName = "Botswana"
                        },
                        new
                        {
                            CountryId = 145,
                            CountryName = "Qatar"
                        },
                        new
                        {
                            CountryId = 146,
                            CountryName = "Gambia"
                        },
                        new
                        {
                            CountryId = 147,
                            CountryName = "Gabon"
                        },
                        new
                        {
                            CountryId = 148,
                            CountryName = "Guinea-Bissau"
                        },
                        new
                        {
                            CountryId = 149,
                            CountryName = "Trinidad and Tobago"
                        },
                        new
                        {
                            CountryId = 150,
                            CountryName = "Estonia"
                        },
                        new
                        {
                            CountryId = 151,
                            CountryName = "Mauritius"
                        },
                        new
                        {
                            CountryId = 152,
                            CountryName = "Swaziland"
                        },
                        new
                        {
                            CountryId = 153,
                            CountryName = "Bahrain"
                        },
                        new
                        {
                            CountryId = 154,
                            CountryName = "Timor-Leste"
                        },
                        new
                        {
                            CountryId = 155,
                            CountryName = "Cyprus"
                        },
                        new
                        {
                            CountryId = 156,
                            CountryName = "Fiji"
                        },
                        new
                        {
                            CountryId = 157,
                            CountryName = "Djibouti"
                        },
                        new
                        {
                            CountryId = 158,
                            CountryName = "Guyana"
                        },
                        new
                        {
                            CountryId = 159,
                            CountryName = "Equatorial Guinea"
                        },
                        new
                        {
                            CountryId = 160,
                            CountryName = "Bhutan"
                        },
                        new
                        {
                            CountryId = 161,
                            CountryName = "Comoros"
                        },
                        new
                        {
                            CountryId = 162,
                            CountryName = "Montenegro"
                        },
                        new
                        {
                            CountryId = 163,
                            CountryName = "Western Sahara"
                        },
                        new
                        {
                            CountryId = 164,
                            CountryName = "Suriname"
                        },
                        new
                        {
                            CountryId = 165,
                            CountryName = "Luxembourg"
                        },
                        new
                        {
                            CountryId = 166,
                            CountryName = "Solomon Islands"
                        },
                        new
                        {
                            CountryId = 167,
                            CountryName = "Cape Verde"
                        },
                        new
                        {
                            CountryId = 168,
                            CountryName = "Malta"
                        },
                        new
                        {
                            CountryId = 169,
                            CountryName = "Brunei"
                        },
                        new
                        {
                            CountryId = 170,
                            CountryName = "Bahamas"
                        },
                        new
                        {
                            CountryId = 171,
                            CountryName = "Maldives"
                        },
                        new
                        {
                            CountryId = 172,
                            CountryName = "Iceland"
                        },
                        new
                        {
                            CountryId = 173,
                            CountryName = "Belize"
                        },
                        new
                        {
                            CountryId = 174,
                            CountryName = "Barbados"
                        },
                        new
                        {
                            CountryId = 175,
                            CountryName = "Vanuatu"
                        },
                        new
                        {
                            CountryId = 176,
                            CountryName = "Samoa"
                        },
                        new
                        {
                            CountryId = 177,
                            CountryName = "Saint Lucia"
                        },
                        new
                        {
                            CountryId = 178,
                            CountryName = "Kiribati"
                        },
                        new
                        {
                            CountryId = 179,
                            CountryName = "Grenada"
                        },
                        new
                        {
                            CountryId = 180,
                            CountryName = "Tonga"
                        },
                        new
                        {
                            CountryId = 181,
                            CountryName = "Federated States of Micronesia"
                        },
                        new
                        {
                            CountryId = 182,
                            CountryName = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            CountryId = 183,
                            CountryName = "Seychelles"
                        },
                        new
                        {
                            CountryId = 184,
                            CountryName = "Antigua and Barbuda"
                        },
                        new
                        {
                            CountryId = 185,
                            CountryName = "Andorra"
                        },
                        new
                        {
                            CountryId = 186,
                            CountryName = "Dominica"
                        },
                        new
                        {
                            CountryId = 187,
                            CountryName = "Liechtenstein"
                        },
                        new
                        {
                            CountryId = 188,
                            CountryName = "Monaco"
                        },
                        new
                        {
                            CountryId = 189,
                            CountryName = "San Marino"
                        },
                        new
                        {
                            CountryId = 190,
                            CountryName = "Palau"
                        },
                        new
                        {
                            CountryId = 191,
                            CountryName = "Tuvalu"
                        },
                        new
                        {
                            CountryId = 192,
                            CountryName = "Nauru"
                        },
                        new
                        {
                            CountryId = 193,
                            CountryName = "Vatican City"
                        });
                });

            modelBuilder.Entity("TaskManager_Core.Domain.Entities.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("ClientLocationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TeamSize")
                        .HasColumnType("int");

                    b.HasKey("ProjectId");

                    b.HasIndex("ClientLocationId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("TaskManager_Core.Domain.Entities.Skill", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillId"));

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("SkillLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SkillId");

                    b.HasIndex("Id");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("TaskManager_Core.Domain.Entities.TaskPriority", b =>
                {
                    b.Property<int>("TaskPriorityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskPriorityId"));

                    b.Property<string>("TaskPriorityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TaskPriorityId");

                    b.ToTable("TaskPriorities");

                    b.HasData(
                        new
                        {
                            TaskPriorityId = 1,
                            TaskPriorityName = "Urgent"
                        },
                        new
                        {
                            TaskPriorityId = 2,
                            TaskPriorityName = "Normal"
                        },
                        new
                        {
                            TaskPriorityId = 3,
                            TaskPriorityName = "Below Normal"
                        },
                        new
                        {
                            TaskPriorityId = 4,
                            TaskPriorityName = "Low"
                        });
                });

            modelBuilder.Entity("TaskManager_Core.Domain.Entities.TaskStatus", b =>
                {
                    b.Property<int>("TaskStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskStatusId"));

                    b.Property<string>("TaskStatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TaskStatusId");

                    b.ToTable("TaskStatus");

                    b.HasData(
                        new
                        {
                            TaskStatusId = 1,
                            TaskStatusName = "Holding"
                        },
                        new
                        {
                            TaskStatusId = 2,
                            TaskStatusName = "Prioritized"
                        },
                        new
                        {
                            TaskStatusId = 3,
                            TaskStatusName = "Started"
                        },
                        new
                        {
                            TaskStatusId = 4,
                            TaskStatusName = "Finished"
                        },
                        new
                        {
                            TaskStatusId = 5,
                            TaskStatusName = "Reverted"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("TaskManager.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("TaskManager.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("TaskManager.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("TaskManager.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskManager.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("TaskManager.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaskManager_Core.Domain.Entities.Project", b =>
                {
                    b.HasOne("TaskManager_Core.Domain.Entities.ClientLocation", "ClientLocation")
                        .WithMany()
                        .HasForeignKey("ClientLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientLocation");
                });

            modelBuilder.Entity("TaskManager_Core.Domain.Entities.Skill", b =>
                {
                    b.HasOne("TaskManager.Identity.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });
#pragma warning restore 612, 618
        }
    }
}
